In [2]:
import numpy as np;

In [3]:
a = np.array([[3,1], [1,2]])

In [4]:
a

array([[3, 1],
       [1, 2]])

In [5]:
b = np.array([9, 8])

In [6]:
x = np.linalg.solve(a, b)

In [7]:
x

array([ 2.,  3.])

In [8]:
np.dot(a, x)

array([ 9.,  8.])

In [9]:
np.dot?

In [12]:
np.dot???

SyntaxError: invalid syntax (<ipython-input-12-92c7779e6fae>, line 1)